### ISSUE TITLE
是不是还有内存泄漏

### ISSUE THREAD

**Issue by teli5200** [hauntek/python-ngrok#11]
昨天刚开机是消耗8M左右内存，跑了12小时变成 15M了。。。

用的是PyInstaller 编译成EXE运行的，运行时有日志不断输出

**Comment by hauntek** [comment]
脚本已经优化到不存在内存泄露！如果内存增加不排除是虚拟机的问题，建议升级python版本试试

**Comment by hauntek** [comment]
有日记不断输出，表示一直有连接访问，说明有人不断访问，不排除你站点正在遭受攻击。

**Comment by teli5200** [comment]
是一直都访问，这个算是正常，请求量不大，我是py3.5.2 ,有可能是日志输出导致的内存问题么？

**Comment by hauntek** [comment]
通过PyInstaller打包的exe，不仅文件大，内存占用也大，属于正常情况。或者你可以下载python环境，直接运行脚本
