### ISSUE TITLE
我想在这个版本上增加websocket穿透

### ISSUE THREAD

**Issue by thinkclaves** [hauntek/python-ngrok#12]
我想用websocket做一个功能，所以想在这个版本上增加websocket穿透，麻烦@hauntek 估测一下开发工作量，还有具体入手点。ngrokd/ngrok都想用你的python版本。网络编程了解不多，能编写非常入门的程序。

**Comment by hauntek** [comment]
websocket暂时没接触过，不过你试试tcp转发websocket看看。
