### ISSUE TITLE
希望加上一个结束的接口

### ISSUE THREAD

**Issue by ctaoist** [hauntek/python-ngrok#16]
首先感谢作者的贡献。

我的程序集成了这个功能，将其放到一个线程中，停不下来。

如果放到一个子进程中，terminate 之后感觉也没有停下来，因为再开已子进程的话，会提示服务器端口已经在使用。

最后，希望线程里可以加上一个结束的信号。

**Comment by hauntek** [comment]
你可以试试Signal 信号

**Comment by hauntek** [comment]
提示服务器端口已经在使用，可以在服务端结束时加个端口释放，或者端口重用试试。
