### ISSUE TITLE
如果绑定其他端口（55035）时， hostname值中的端口号去掉

### ISSUE THREAD

**Issue by yzhbigdata** [hauntek/python-ngrok#17]
`def getloacladdr(Tunnels, Url):
    protocol = Url[0:Url.find(':')]
    hostname = Url[Url.find('//') + 2:]
    if str(hostname).find(":")>-1:
        hostname=hostname[0:hostname.find(':')]`

如果绑定其他端口时， hostname值中的端口号去掉【受影响的代码 if tunnelinfo.get('hostname') == hostname 】
eg：aaaa.bbb.cn:55035

**Comment by hauntek** [comment]
这个查询隧道信息出现的问题，近期我会修复。

**Comment by hauntek** [comment]
python-ngrok v1.5(2018/09/19)版本已修复该问题。
