### ISSUE TITLE
TCP转发bug

### ISSUE THREAD

**Issue by dapao9999** [hauntek/python-ngrok#2]
你好，用python-ngrok开tcp转发国外的ss，转发后能打开youtube，但是无法播放，不知道是不是bug。其他的网站没有问题，用的是python版的ss。

**Comment by hauntek** [comment]
建议加大吞吐量，bufsize = 8192 # 吞吐量

________________________________
发件人: dcdc8888 <notifications@github.com>
发送时间: 2017年1月12日 12:28:55
收件人: hauntek/python-ngrok
抄送: Subscribed
主题: [hauntek/python-ngrok] TCP转发bug (#2)


你好，用python-ngrok开tcp转发国外的ss，转发后能打开youtube，但是无法播放，不知道是不是bug。其他的网站没有问题，用的是python版的ss。

―

**Comment by dapao9999** [comment]
感谢，可以了!

在 2017年1月13日 上午3:56，hauntek <notifications@github.com>写道：

**Comment by dapao9999** [comment]
看视频速度很快，但是发现facebook的评论加载不出来，一直转圈。
![2017-02-13_222917](https://cloud.githubusercontent.com/assets/6910161/22887169/f4d7827c-f23b-11e6-9d26-1d991eb9e680.png)

**Comment by hauntek** [comment]
这个问题我也发现了，已经修复了
