### ISSUE TITLE
请问路由器（mipsle）的话怎么使用呢？

### ISSUE THREAD

**Issue by onlyJinx** [hauntek/python-ngrok#22]
我用原版ngrok编译的10M可以运行太大了，想用个体积小一点的，路由器固件才64M，或者有什么关键词给我去Google一下，哈哈

**Comment by hauntek** [comment]
如果路由器是openwrt的话，你可以命令看下openwrt是否已经集成python，在命令输入python 看看是否会显示python 版本，如果openwrt确认集成python，把脚本上传路由器，然后在脚本路径下输入命令 `python python-ngrok.py`

**Comment by hauntek** [comment]
或者你也可以通过预设的配置文件启动脚本 `./python-ngrok.py ngrok.config`  记得设置权限755

**Comment by onlyJinx** [comment]
> 或者你也可以通过预设的配置文件启动脚本 `./python-ngrok.py ngrok.config` 记得设置权限755

我的垃圾路由器没有集成python，内存才64，有没有办法把这个文件做成编译好的那种。。。

**Comment by hauntek** [comment]
可以在其他平台交叉编译ngrok-c

https://github.com/dosgo/ngrok-c

**Comment by onlyJinx** [comment]
> 可以在其他平台交叉编译ngrok-c
> 
> https://github.com/dosgo/ngrok-c

哈哈，我就是在这个c语言版的得知这个python的，因为编译过程不顺利才来这边问问的，谢谢啦～
