### ISSUE TITLE
我自己编译架设了服务端，如何用这个做客户端

### ISSUE THREAD

**Issue by zhuaiice** [hauntek/python-ngrok#8]
我自己编译架设了服务端，版本也是1.7的，内存泄漏严重，如何用这个做客户端？？谢谢

**Comment by hauntek** [comment]
![image](https://cloud.githubusercontent.com/assets/17927997/26140581/3a693904-3b0a-11e7-9035-294f0321967b.png)
在Ngrok服务器地址输入你服务器的IP地址，然后下面配置隧道就可以用了。

**Comment by zhuaiice** [comment]
非常谢谢，我就改了下程序文件的服务器地址，其他都是在那个config配置文件里面修改的！可以用了！稳定性在测试看看！原版编译的arm客户端，在http下面文件传输的时候，大文件和多个文件传输很容易就奔溃了！
